apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-local-storage
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-lpv-cn-east-shanghai-01
  labels:
    topology.kubernetes.io/region: cn-east
    topology.kubernetes.io/zone: cn-east-shanghai
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /mnt/minio-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
                - cn-east

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-lpv-cn-east-shanghai-02
  labels:
    topology.kubernetes.io/region: cn-east
    topology.kubernetes.io/zone: cn-east-shanghai
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /mnt/minio-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
                - cn-east

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-lpv-cn-east-shanghai-03
  labels:
    topology.kubernetes.io/region: cn-east
    topology.kubernetes.io/zone: cn-east-shanghai
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /mnt/minio-3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
                - cn-east


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-lpv-cn-east-shanghai-04
  labels:
    topology.kubernetes.io/region: cn-east
    topology.kubernetes.io/zone: cn-east-shanghai
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /mnt/minio-4
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
                - cn-east

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-lpv-cn-west-chengdu-01
  labels:
    topology.kubernetes.io/region: cn-west
    topology.kubernetes.io/zone: cn-west-chengdu
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /mnt/minio-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
                - cn-west

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-lpv-cn-west-chengdu-02
  labels:
    topology.kubernetes.io/region: cn-west
    topology.kubernetes.io/zone: cn-west-chengdu
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /mnt/minio-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
                - cn-west


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-lpv-cn-west-chengdu-03
  labels:
    topology.kubernetes.io/region: cn-west
    topology.kubernetes.io/zone: cn-west-chengdu
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /mnt/minio-3
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
                - cn-west

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-lpv-cn-west-chengdu-04
  labels:
    topology.kubernetes.io/region: cn-west
    topology.kubernetes.io/zone: cn-west-chengdu
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: minio-local-storage
  local:
    path: /mnt/minio-4
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: topology.kubernetes.io/region
              operator: In
              values:
                - cn-west