hosts:
  - { hostname: lwy-cn-cd-tpy-std-1721667201, address: 172.16.67.201, internal: 172.16.67.201, port: 22, username: root, password: lwy67201, workdir: /root/k8s, private_key: "", passphrase: "" }
  - { hostname: lwy-cn-cd-tpy-std-1721667202, address: 172.16.67.202, internal: 172.16.67.202, port: 22, username: root, password: lwy67202, workdir: /root/k8s, private_key: "", passphrase: "" }
  - { hostname: lwy-cn-cd-tpy-std-1721667203, address: 172.16.67.203, internal: 172.16.67.203, port: 22, username: root, password: lwy67203, workdir: /root/k8s, private_key: "", passphrase: "" }

config:
  k8s:
    version: "1.30.0"
    cluster_name: "alpha"
    control_plane_endpoint:
      balancer: "haproxy"
      domain: "k8s.api-server.lb"
      address: "172.16.67.204"
      port: "9443"
      sans: []
    image_repository: "registry.aliyuncs.com/google_containers"
    # 一下三个决定了集群规模
    # 集群最大节点数: 2^(node_cidr_mask_size-pod_subnet(cidr))
    # 每个节点最大ip数: 2^(32-node_cidr_mask_size)
    # 例：2^(24-12) = 4096(节点数) 2^(32-24) = 256(ip数)
    service_subnet: "10.16.0.0/12"
    pod_subnet: "10.128.0.0/12"
    node_cidr_mask_size: "24"
    ipvs_exclude_cidr: [ "172.16.0.0/24" ]
    kube_proxy_port_range: "0-0"
    service_node_port_range: "30000-32767"
    #cluster_dns: ["61.139.2.69", "211.137.96.205"]
    certificate_key: "9298778de88f1a0cb63823dba01e33e6d057358a01ad429a9b739bf79844b756"
    bootstrap_token: "cb6xll.lo5z8trai8zwzh7t"
    untainted: "control-plane" # "control-plane"

  containerd:
    arch: "amd64"
    version: "1.7.15"
    runc_version: "1.1.12"
    cni_version: "1.4.1"
    cri_ctl_version: "1.30.0"
    sand_box_image: "registry.aliyuncs.com/google_containers/pause:3.9"
    certs_d:
      docker.io:
        server: https://docker.io
        mirror:
          - address: https://harbor.silvacheung.com/v2/docker.io
            capabilities: [ pull, resolve ]
            override_path: true
            skip_tls_verify: true
        header:
          https://harbor.silvacheung.com:
            - Authorization = [ "Basic YWRtaW46MTIzNDU2" ]
      quay.io:
        server: https://quay.io
        mirror:
          - address: https://harbor.silvacheung.com/v2/quay.io
            capabilities: [ pull, resolve ]
            override_path: true
            skip_tls_verify: true
        header:
          https://harbor.silvacheung.com:
            - Authorization = [ "Basic YWRtaW46MTIzNDU2" ]
      gcr.io:
        server: https://gcr.io
        mirror:
          - address: https://harbor.silvacheung.com/v2/gcr.io
            capabilities: [ pull, resolve ]
            override_path: true
            skip_tls_verify: true
        header:
          https://harbor.silvacheung.com:
            - Authorization = [ "Basic YWRtaW46MTIzNDU2" ]
      k8s.gcr.io:
        server: https://k8s.gcr.io
        mirror:
          - address: https://harbor.silvacheung.com/v2/k8s.gcr.io
            capabilities: [ pull, resolve ]
            override_path: true
            skip_tls_verify: true
        header:
          https://harbor.silvacheung.com:
            - Authorization = [ "Basic YWRtaW46MTIzNDU2" ]
      registry.k8s.io:
        server: https://registry.k8s.io
        mirror:
          - address: https://harbor.silvacheung.com/v2/registry.k8s.io
            capabilities: [ pull, resolve ]
            override_path: true
            skip_tls_verify: true
        header:
          https://harbor.silvacheung.com:
            - Authorization = [ "Basic YWRtaW46MTIzNDU2" ]
      registry.cluster:
        server: https://harbor.silvacheung.com
        mirror:
          - address: https://harbor.silvacheung.com/v2/registry.cluster
            capabilities: [ pull, resolve ]
            override_path: true
            skip_tls_verify: true
        header:
          https://harbor.silvacheung.com:
            - Authorization = [ "Basic YWRtaW46MTIzNDU2" ]
    auths:
      # 如果是mirror需要auth则必须配置mirror的host(ip:port/domain:port)
      harbor.silvacheung.com:
        username: "username"
        password: "password"
        auth: ""
        identity_token: ""

sftp:
  lwy-cn-cd-tpy-std-1721667201:
    - F:\cri\
    - F:\cni\
  lwy-cn-cd-tpy-std-1721667202:
    - F:\cri\
    - F:\cni\
  lwy-cn-cd-tpy-std-1721667203:
    - F:\cri\
    - F:\cni\

await:
  lwy-cn-cd-tpy-std-1721667202:
    - "lwy-cn-cd-tpy-std-1721667201"
  lwy-cn-cd-tpy-std-1721667203:
    - "lwy-cn-cd-tpy-std-1721667201"

script:
  - yaml/kubernetes/v1.30/control-plane/set-resolv-conf.sh
  - yaml/kubernetes/v1.30/control-plane/set-apt.sh
  - yaml/kubernetes/v1.30/control-plane/set-pre-check.sh
  - yaml/kubernetes/v1.30/control-plane/set-hostname.sh
  - yaml/kubernetes/v1.30/control-plane/set-lb-config.sh
  - yaml/kubernetes/v1.30/control-plane/set-lb-install.sh
  - yaml/kubernetes/v1.30/control-plane/set-hosts.sh
  - yaml/kubernetes/v1.30/control-plane/set-os-system.sh
  - yaml/kubernetes/v1.30/control-plane/set-ntp-server.sh
  - yaml/kubernetes/v1.30/control-plane/set-containerd.sh
  - yaml/kubernetes/v1.30/control-plane/set-kubeadm.sh
  - yaml/kubernetes/v1.30/control-plane/set-haproxy.sh
  - yaml/kubernetes/v1.30/control-plane/set-kube-vip.sh
  - yaml/kubernetes/v1.30/control-plane/set-k8s-config.sh
  - yaml/kubernetes/v1.30/control-plane/set-k8s-audit.sh
  - yaml/kubernetes/v1.30/control-plane/set-k8s-boot.sh
  - yaml/kubernetes/v1.30/control-plane/set-k8s-security.sh
  - yaml/kubernetes/v1.30/control-plane/set-cni-cilium.sh
  - yaml/kubernetes/v1.30/control-plane/set-k8s-optimize.sh
