hosts:
  - enp3s0://root:lwy67201@172.16.67.201:22/?hostname=lwy-cn-cd-tpy-std-1721667201&internal=172.16.67.201&workdir=/root/.ssh-pty/scripts
  - enp3s0://root:lwy67202@172.16.67.202:22/?hostname=lwy-cn-cd-tpy-std-1721667202&internal=172.16.67.202&workdir=/root/.ssh-pty/scripts
  - enp3s0://root:lwy67203@172.16.67.203:22/?hostname=lwy-cn-cd-tpy-std-1721667203&internal=172.16.67.203&workdir=/root/.ssh-pty/scripts

configs:
  K8s:
    Version: "1.29.0"
    ClusterName: "test"
    ControlPlaneEndpoint:
      Domain: "172.16.67.202"
      Port: "9433"
    ImageRepository: "registry.aliyuncs.com/google_containers"
    Etcd:
      ImageRepository: "registry.aliyuncs.com/google_containers"
      ImageTag: ""
    Coredns:
      ImageRepository: "registry.aliyuncs.com/google_containers"
      ImageTag: ""
    ServiceSubnet: "10.96.0.0/16"
    PodSubnet: "10.244.0.0/24"
    NodeCidrMaskSize: "25"
    IPVSExcludeCIDRs: ["172.16.0.0/24"]
    CertificateKey: ""
    BootstrapToken: ""
    ControlPlanes:
      - "lwy-cn-cd-tpy-std-1721667201"
      - "lwy-cn-cd-tpy-std-1721667202"
      - "lwy-cn-cd-tpy-std-1721667203"

  Containerd:
    Arch: "amd64"
    Version: "1.7.15"
    SandBoxImage: "registry.aliyuncs.com/google_containers/pause:3.9"
    Mirrors:
      docker.io: https://registry.aliyuncs.com
      k8s.gcr.io: https://registry.aliyuncs.com/google_containers
    InsecureRegistries: []
    Auths:
      xxxx.aliyuncs.com:
        Username: XXX
        Password: "xxx"
        CAFile: ""
        CertFile: ""
        KeyFile: ""
        SkipTLSVerify: true

  Runc:
    Arch: "amd64"
    Version: "1.1.12"

  CNIPlugins:
    Arch: "amd64"
    Version: "1.4.1"

  Crictl:
    Arch: "amd64"
    Version: "1.29.0"

scripts:
  - D:\workspace\ssh-pty\yamls\kubernetes\set-resolv-conf.sh
  #  - D:\workspace\ssh-pty\yamls\kubernetes\set-apt.sh
  - D:\workspace\ssh-pty\yamls\kubernetes\set-hostname.sh
  - D:\workspace\ssh-pty\yamls\kubernetes\set-hosts.sh
  - D:\workspace\ssh-pty\yamls\kubernetes\set-pre-check.sh
  - D:\workspace\ssh-pty\yamls\kubernetes\set-os-system.sh
  - D:\workspace\ssh-pty\yamls\kubernetes\set-ntp-server.sh
  - D:\workspace\ssh-pty\yamls\kubernetes\set-containerd.sh
  - D:\workspace\ssh-pty\yamls\kubernetes\set-kubeadm.sh
  - D:\workspace\ssh-pty\yamls\kubernetes\set-k8s-config.sh
  - D:\workspace\ssh-pty\yamls\kubernetes\set-k8s-audit.sh
#  - ./set-k8s-lb.sh
#  - ./set-k8s-boot.sh
#  - ./set-k8s-join.sh
#  - ./get-k8s-info.sh

#special:
#  pc-1721601:
#    - /ssh-pty/conf/xxx.sh
