hosts:
  - { hostname: lwy-cn-cd-tpy-std-172166771, address: 172.16.67.71, internal: 172.16.67.71, port: 22, username: root, password: cgm123., workdir: /root/k8s, private_key: "", passphrase: "" }

config:
  metrics-server:
    enable: false
    version: 3.12.1
    replicas: 1
    service_monitor: false

  nfs:
    enable: false
    version:  4.0.18
    server: 172.16.67.253
    path: /mnt/nas-data/k8s-nfs
    replicas: 1
    mnt_options:
      - nfsvers=4

  cert-manager:
    enable: false
    version: v1.15.1
    replicas: 1

  prometheus-stack:
    enable: false
    version: 60.4.0
    replicas: 1
    use_cert_manager: true
    kube_version_override: 1.30.0
    grafana_admin_password: gfa@12345
    storage_class_name: nfs-subdir-external

  harbor:
    enable: false
    version: 1.15.0
    replicas: 1
    node_port_http: 30080
    node_port_https: 30443
    external_url: https://app-oci.registry.cluster:30443
    admin_password: Harbor12345
    storage_class_name: nfs-subdir-external
    storage_size_registry: 5Gi
    storage_size_job_service: 5Gi
    storage_size_database: 5Gi
    storage_size_redis: 5Gi
    storage_size_trivy: 5Gi
    service_monitor: false

  ipam-gateway:
    enable: false
    version: 1.0.0
    ip_cidr: 20.10.0.0/16
    registry: example.com
    repository: ipam-gateway/ipam-svc-controller
    registry_username: admin
    registry_password: 123456
    nodes: []

script:
  - yaml/kubernetes/v1.30/k8s-addons/x-ipam-gateway.sh
  - yaml/kubernetes/v1.30/k8s-addons/x-storage-nfs.sh
  - yaml/kubernetes/v1.30/k8s-addons/x-cert-manager.sh
  - yaml/kubernetes/v1.30/k8s-addons/x-prometheus-stack.sh
  - yaml/kubernetes/v1.30/k8s-addons/x-metrics-server.sh
  - yaml/kubernetes/v1.30/k8s-addons/x-registry-harbor.sh
  - yaml/kubernetes/v1.30/k8s-addons/x-final-echo.sh
