hosts:
#  - { hostname: lwy-cn-cd-tpy-std-1721667201, address: 172.16.67.201, internal: 172.16.67.201, port: 22, username: root, password: lwy67201, workdir: /root/k8s, private_key: "", passphrase: "" }
#  - { hostname: lwy-cn-cd-tpy-std-1721667202, address: 172.16.67.202, internal: 172.16.67.202, port: 22, username: root, password: lwy67202, workdir: /root/k8s, private_key: "", passphrase: "" }
  - { hostname: lwy-cn-cd-tpy-std-1721667203, address: 172.16.67.203, internal: 172.16.67.203, port: 22, username: root, password: lwy67203, workdir: /root/k8s, private_key: "", passphrase: "" }

config:
  k8s:
    version: "1.30.0"
    control_plane_endpoint:
      domain: "k8s.api-server.lb"
      address: "172.16.67.204"
      port: "9443"
    # 主节点执行 kubeadm init phase upload-certs --upload-certs --config /etc/kubernetes/kubeadm-config.yaml
    certificate_key: "9298778de88f1a0cb63823dba01e33e6d057358a01ad429a9b739bf79844b756"
    # 主节点执行 kubeadm token create --description 'kubeadm bootstrap token' --ttl 2h0m0s --usages authentication,signing --groups system:bootstrappers:kubeadm:default-node-token
    bootstrap_token: "cb6xll.lo5z8trai8zwzh7t"

  containerd:
    arch: "amd64"
    version: "1.7.15"
    runc_version: "1.1.12"
    cni_version: "1.4.1"
    cri_ctl_version: "1.30.0"
    sand_box_image: "registry.aliyuncs.com/google_containers/pause:3.9"
    registry:
      docker.io:
        server: https://docker.io
        mirror: https://registry.harbor.core/v2/docker.io
        override_path: true
      gcr.io:
        server: https://gcr.io
        mirror: https://registry.harbor.core/v2/gcr.io
        override_path: true
      quay.io:
        server: https://quay.io
        mirror: https://registry.harbor.core/v2/quay.io
        override_path: true
      k8s.gcr.io:
        server: https://k8s.gcr.io
        mirror: https://registry.harbor.core/v2/k8s.gcr.io
        override_path: true
      registry.k8s.io:
        server: https://registry.k8s.io
        mirror: https://registry.harbor.core/v2/registry.k8s.io
        override_path: true
      registry.harbor.local:
        server: https://registry.harbor.core
        mirror: https://172.16.67.100:443
        capabilities: [pull, push, resolve]
        override_path: false
        skip_tls_verify: false
        ca_file: "ca_file"
        cert_file: "cert_file"
        key_file: "key_file"
        headers:
          Authorization: ["Basic YWRtaW46MTIzNDU2"]
          x-custom-0: ["foo", "bar"]
    auths:
      registry.harbor.core:
        username: "username"
        password: "password"
        auth: ""
        identity_token: ""

sftp:
  lwy-cn-cd-tpy-std-1721667201:
    - F:\cri\
  lwy-cn-cd-tpy-std-1721667202:
    - F:\cri\
  lwy-cn-cd-tpy-std-1721667203:
    - F:\cri\

script:
  - yaml/kubernetes/v1.30/worker-node/set-resolv-conf.sh
  - yaml/kubernetes/v1.30/worker-node/set-apt.sh
  - yaml/kubernetes/v1.30/worker-node/set-pre-check.sh
  - yaml/kubernetes/v1.30/worker-node/set-hostname.sh
  - yaml/kubernetes/v1.30/worker-node/set-hosts.sh
  - yaml/kubernetes/v1.30/worker-node/set-os-system.sh
  - yaml/kubernetes/v1.30/worker-node/set-ntp-server.sh
  - yaml/kubernetes/v1.30/worker-node/set-containerd.sh
  - yaml/kubernetes/v1.30/worker-node/set-kubeadm.sh
  - yaml/kubernetes/v1.30/worker-node/set-k8s-config.sh
  - yaml/kubernetes/v1.30/worker-node/set-k8s-audit.sh
  - yaml/kubernetes/v1.30/worker-node/set-k8s-boot.sh
  - yaml/kubernetes/v1.30/worker-node/set-k8s-security.sh
