hosts:
#  - { hostname: lwy-cn-cd-tpy-std-1721667201, address: 172.16.67.201, internal: 172.16.67.201, port: 22, username: root, password: lwy67201, workdir: /root/k8s, private_key: "", passphrase: "" }
#  - { hostname: lwy-cn-cd-tpy-std-1721667202, address: 172.16.67.202, internal: 172.16.67.202, port: 22, username: root, password: lwy67202, workdir: /root/k8s, private_key: "", passphrase: "" }
  - { hostname: lwy-cn-cd-tpy-std-1721667203, address: 172.16.67.203, internal: 172.16.67.203, port: 22, username: root, password: lwy67203, workdir: /root/k8s, private_key: "", passphrase: "" }

config:
  k8s:
    version: "1.30.0"
    control_plane_endpoint:
      domain: "k8s.api-server.lb"
      address: "172.16.67.204"
      port: "9443"
    # 主节点执行 kubeadm init phase upload-certs --upload-certs --config /etc/kubernetes/kubeadm-config.yaml
    certificate_key: "9298778de88f1a0cb63823dba01e33e6d057358a01ad429a9b739bf79844b756"
    # 主节点执行 kubeadm token create --description 'kubeadm bootstrap token' --ttl 2h0m0s --usages authentication,signing --groups system:bootstrappers:kubeadm:default-node-token
    bootstrap_token: "cb6xll.lo5z8trai8zwzh7t"

  containerd:
    arch: "amd64"
    version: "1.7.15"
    runc_version: "1.1.12"
    cni_version: "1.4.1"
    sand_box_image: "registry.aliyuncs.com/google_containers/pause:3.9"
    certs_d:
      docker.io:
        server: https://docker.io
        mirror:
          - address: https://harbor.silvacheung.com/v2/docker.io
            capabilities: [ pull, resolve ]
            override_path: true
            skip_tls_verify: false
        header:
          https://harbor.silvacheung.com:
            - Authorization = [ "Basic YWRtaW46MTIzNDU2" ]
      quay.io:
        server: https://quay.io
        mirror:
          - address: https://harbor.silvacheung.com/v2/quay.io
            capabilities: [ pull, resolve ]
            override_path: true
            skip_tls_verify: false
        header:
          https://harbor.silvacheung.com:
            - Authorization = [ "Basic YWRtaW46MTIzNDU2" ]
      gcr.io:
        server: https://gcr.io
        mirror:
          - address: https://harbor.silvacheung.com/v2/gcr.io
            capabilities: [ pull, resolve ]
            override_path: true
            skip_tls_verify: false
        header:
          https://harbor.silvacheung.com:
            - Authorization = [ "Basic YWRtaW46MTIzNDU2" ]
      k8s.gcr.io:
        server: https://k8s.gcr.io
        mirror:
          - address: https://harbor.silvacheung.com/v2/k8s.gcr.io
            capabilities: [ pull, resolve ]
            override_path: true
            skip_tls_verify: false
        header:
          https://harbor.silvacheung.com:
            - Authorization = [ "Basic YWRtaW46MTIzNDU2" ]
      ghcr.io:
        server: https://ghcr.io
        mirror:
          - address: https://harbor.silvacheung.com/v2/ghcr.io
            capabilities: [ pull, resolve ]
            override_path: true
            skip_tls_verify: false
        header:
          https://harbor.silvacheung.com:
            - Authorization = [ "Basic YWRtaW46MTIzNDU2" ]
      registry.k8s.io:
        server: https://registry.k8s.io
        mirror:
          - address: https://harbor.silvacheung.com/v2/registry.k8s.io
            capabilities: [ pull, resolve ]
            override_path: true
            skip_tls_verify: false
        header:
          https://harbor.silvacheung.com:
            - Authorization = [ "Basic YWRtaW46MTIzNDU2" ]
      registry.k8s.cluster:
        server: https://harbor.silvacheung.com
        mirror:
          - address: https://harbor.silvacheung.com/v2/registry.k8s.cluster
            capabilities: [ pull, push, resolve ]
            override_path: true
            skip_tls_verify: false
        header:
          https://harbor.silvacheung.com:
            - Authorization = [ "Basic YWRtaW46MTIzNDU2" ]
    auths:
      # 如果是mirror需要auth则必须配置mirror的host(ip:port/domain:port)
      harbor.silvacheung.com:
        username: "username"
        password: "password"
        auth: ""
        identity_token: ""

sftp:
  lwy-cn-cd-tpy-std-1721667201:
    - F:\cri\
  lwy-cn-cd-tpy-std-1721667202:
    - F:\cri\
  lwy-cn-cd-tpy-std-1721667203:
    - F:\cri\

script:
  - yaml/kubernetes/v1.30/control-plane/set-pre-check.sh
  - yaml/kubernetes/v1.30/control-plane/set-resolv-conf.sh
  - yaml/kubernetes/v1.30/control-plane/set-apt.sh
  - yaml/kubernetes/v1.30/control-plane/set-hosts.sh
  - yaml/kubernetes/v1.30/control-plane/set-hostname.sh
  - yaml/kubernetes/v1.30/worker-node/set-os-system.sh
  - yaml/kubernetes/v1.30/worker-node/set-ntp-server.sh
  - yaml/kubernetes/v1.30/control-plane/set-containerd-config.sh
  - yaml/kubernetes/v1.30/control-plane/set-containerd-install.sh
  - yaml/kubernetes/v1.30/worker-node/set-kubeadm.sh
  - yaml/kubernetes/v1.30/worker-node/set-k8s-config.sh
  - yaml/kubernetes/v1.30/worker-node/set-k8s-audit.sh
  - yaml/kubernetes/v1.30/worker-node/set-k8s-boot.sh
  - yaml/kubernetes/v1.30/worker-node/set-k8s-security.sh
  - yaml/kubernetes/v1.30/worker-node/set-final-echo.sh
